pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                checkout scm
            }
        }

        stage('Build JAR') {
            steps {
                sh "./mvnw clean package"
            }
        }

        stage('Archive Artifact') {
            steps {
                archiveArtifacts artifacts: 'initial/target/*.jar', fingerprint: true
            }
        }
    }
}
