pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                checkout scm
            }
        }

        stage('Build JAR') {
            steps {
                sh "chmod +x initial/mvnw"
                sh "cd initial && ./mvnw clean package"
            }
        }

        stage('Upload to Nexus') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'nexus-admin', usernameVariable: 'USR', passwordVariable: 'PASS')]) {
                    sh """
                        cd initial
                        JAR_FILE=\$(ls target/*-SNAPSHOT.jar)

                        curl -v -u $USR:$PASS \
                        --upload-file \$JAR_FILE \
                        http://host.docker.internal:8081/repository/maven-releases/com/example/app/1.0.0/app-1.0.0.jar
                    """
                }
            }
        }

        stage('Archive Artifact') {
            steps {
                archiveArtifacts artifacts: 'initial/target/*.jar', fingerprint: true
            }
        }
    }
}
